language: python
python:
  - "2.6"
  - "2.7"
  - "3.4"
env:
  - DJANGO=1.5.12
  - DJANGO=1.6.11
  - DJANGO=1.7.7
  - DJANGO=1.8
matrix:
  exclude:
    - python: "2.6"
      env: DJANGO=1.5.12
    - python: "2.6"
      env: DJANGO=1.7.7
    - python: "2.6"
      env: DJANGO=1.8
    - python: "3.4"
      env: DJANGO=1.5.12
    - python: "3.4"
      env: DJANGO=1.6.11
    - python: "3.4"
      env: DJANGO=1.7.7
install:
  - pip install -q Django==$DJANGO --use-mirrors
  - pip install coveralls
  - pip install -r test_requirements.pip
script:
  - coverage run --source=rest_auth setup.py test
after_success:
  - coveralls
before_script:
  - flake8 . --config=flake8
